### ISSUE TITLE
NETWORK_TIP_V1.mat don't exist on the repository

### ISSUE THREAD

**Issue by berlius** [Parkdaeyoung/Colorization-project#1]
Error using load
Unable to read file 'colorization_model/NETWORK_TIP_V1.mat'. No such file or directory.

Error in demo_single (line 7)
    load('colorization_model/NETWORK_TIP_V1.mat')

thanks in advance

**Comment by jsjason** [comment]
I do have a local version of that file, but I doubt it will make the example code work; a lot more setup is required to run the examples. Moreover, this repo was for a class term project, which has been finished a few months ago, and I am no longer willing to maintain this up-to-date. @Parkdaeyoung may have a different opinion..

**Comment by Parkdaeyoung** [comment]
So am I in the same opinion with @jsjason. Refer to the paper "Deep Colorization" by Cheng, upon which our work is based, if you are intereted in. Hope you find out whatever you need :)

**Comment by berlius** [comment]
thank you
